### ISSUE TITLE
Rasti "dviračiai" sąlygą

### ISSUE THREAD

**Issue by sakram07** [sakram07/ProgramavimoOlimpiados#4]
Radau sprendimą, neprisimenu iš kur sąlyga.

**Comment by ignaloidas** [comment]
Ne LMIO, ten nieko susijusio su dviračiais nėra

**Comment by sakram07** [comment]
Gali būti, kad pavadinimas kitoks, bet aš esu 90% įsitikinęs, kad ten iš LMIO
